# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6f97d3391fc42fa72814c035413fa8b2844c2fdb5df791bad944613f94f1c2f194883781e58889a2f988735a0e09882e4cdbc74db727a63a939b95f11da8c93

test:
  secret_key_base: 6b422bae1f6c9c131bfde9ed955fc9e8169a3e9905dfea23602c2d8b5a770a9c562300681bca1436933d18cb85a7df9d44b6b06ef6a297c534715ff854b221f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
